module.exports = {
    "rules": {
        "at-rule-empty-line-before": [ 2, "always", {
            except: ["blockless-group", "all-nested"]
        }],
        "at-rule-no-vendor-prefix": 2,
        "block-closing-brace-newline-after": [ 2, "always-multi-line" ],
        "block-closing-brace-newline-before": [ 2, "always-multi-line" ],
        "block-closing-brace-space-after": [ 2, "always-single-line" ],
        "block-closing-brace-space-before": [ 2, "always-single-line" ],
        "block-no-empty": 2,
        "block-opening-brace-newline-after": [ 2, "always-multi-line" ],
        "block-opening-brace-newline-before": [ 2, "always-single-line" ],
        "block-opening-brace-space-after": [ 2, "always-single-line" ],
        "block-opening-brace-space-before": [ 2, "always-single-line" ],
        "color-hex-case": [ 2, "lower" ],
        "color-hex-length": [ 2, "short" ],
        "color-no-invalid-hex": 2,
        "comment-empty-line-before": [ 2, "never" ],
        "declaration-bang-space-after": [ 2, "never" ],
        "declaration-bang-space-before": [ 2, "always" ],
        "declaration-block-semicolon-newline-after": [ 2, "always" ],
        "declaration-block-semicolon-newline-before": [ 2, "never-multi-line" ],
        "declaration-block-semicolon-space-after": [ 2, "always-single-line" ],
        "declaration-block-semicolon-space-before": [ 2, "never" ],
        "declaration-colon-space-after": [ 2, "always" ],
        "declaration-colon-space-before": [ 2, "never" ],
        "function-calc-no-unspaced-operator": 2,
        "function-comma-space-after": [ 2, "always" ],
        "function-comma-space-before": [ 2, "never" ],
        "function-parentheses-space-inside": [ 2, "never" ],
        "function-space-after": [ 2, "always" ],
        "function-url-quotes": [ 2, "double" ],
        "indentation": [ 4, 4 ],
        "media-feature-colon-space-after": [ 2, "always" ],
        "media-feature-colon-space-before": [ 2, "never" ],
        "media-feature-name-no-vendor-prefix": 2,
        "media-feature-range-operator-space-after": [ 2, "always" ],
        "media-feature-range-operator-space-before": [ 2, "always" ],
        "media-query-list-comma-newline-after": [ 2, "always-multi-line" ],
        "media-query-list-comma-space-after": [ 2, "always-single-line" ],
        "media-query-list-comma-space-before": [ 2, "never" ],
        "media-query-parentheses-space-inside": [ 2, "never" ],
        "nesting-block-opening-brace-newline-before": [ 2, "always-multi-line" ],
        "nesting-block-opening-brace-space-before": [ 2, "always-single-line" ],
        "no-eol-whitespace": 2,
        "no-missing-eof-newline": 0,
        "no-multiple-empty-lines": 2,
        "number-leading-zero": [ 2, "always" ],
        "number-no-trailing-zeros": 2,
        "number-zero-length-no-unit": 2,
        "property-no-vendor-prefix": 2,
        "root-no-standard-properties": 2,
        "rule-no-shorthand-property-overrides": 2,
        "rule-nested-empty-line-before": [ 2, "always-multi-line", {
            except: ["first-nested"]
        }],
        "rule-non-nested-empty-line-before": [ 2, "always-multi-line" ],
        "rule-properties-order": [ 2, [

            // Strong properties (for easy debugging)
            "content",
            "opacity",
            "visibility",
            "overflow",
            "overflow-x",
            "overflow-y",
            "clear",
            "clip",
            "float",
            "display",
            "vertical-align",
            "box-sizing",
            "position",

            // Basic box properties
            "top",
            "right",
            "bottom",
            "left",
            "width",
            "max-width",
            "min-width",
            "height",
            "max-height",
            "min-height",
            "margin",
            "margin-top",
            "margin-right",
            "margin-bottom",
            "margin-left",
            "padding",
            "padding-top",
            "padding-right",
            "padding-bottom",
            "padding-left",

            // Flexible layout properties
            "align-content",
            "align-items",
            "align-self",
            "flex",
            "flex-basis",
            "flex-direction",
            "flex-flow",
            "flex-grow",
            "flex-shrink",
            "flex-wrap",
            "justify-content",
            "order",

            // Multi-column layout properties
            "break-after",
            "break-before",
            "break-inside",
            "column-count",
            "column-fill",
            "column-gap",
            "column-rule",
            "column-rule-color",
            "column-rule-style",
            "column-rule-width",
            "column-span",
            "column-width",
            "columns",
            "widows",

            // Table properties
            "border-collapse",
            "border-spacing",
            "caption-side",
            "empty-cells",
            "table-layout",

            // Basic UI properties
            "cursor",
            "ime-mode",
            "nav-down",
            "nav-index",
            "nav-left",
            "nav-right",
            "nav-up",
            "outline",
            "outline-color",
            "outline-offset",
            "outline-style",
            "outline-width",
            "resize",
            "user-select",

            // Lists and counters properties
            "counter-increment",
            "counter-reset",
            "list-style",
            "list-style-image",
            "list-style-position",
            "list-style-type",

            // Paged media properties
            "orphans",
            "page-break-after",
            "page-break-before",
            "page-break-inside",
            "marks",
            "quotes",

            // Text properties
            "color",
            "direction",
            "font",
            "font-family",
            "font-feature-settings",
            "font-kerning",
            "font-language-override",
            "font-size",
            "font-size-adjust",
            "font-stretch",
            "font-style",
            "font-synthesis",
            "font-variant",
            "font-variant-alternates",
            "font-variant-caps",
            "font-variant-east-asian",
            "font-variant-ligatures",
            "font-variant-numeric",
            "font-variant-position",
            "font-weight",
            "hanging-punctuation",
            "hyphens",
            "letter-spacing",
            "line-break",
            "line-height",
            "overflow-wrap",
            "tab-size",
            "text-align",
            "text-align-last",
            "text-combine-upright",
            "text-decoration",
            "text-decoration-color",
            "text-decoration-line",
            "text-decoration-style",
            "text-indent",
            "text-justify",
            "text-orientation",
            "text-overflow",
            "text-shadow",
            "text-transform",
            "text-underline-position",
            "unicode-bidi",
            "white-space",
            "word-break",
            "word-spacing",
            "word-wrap",
            "writing-mode",

            // Animation properties
            "animation",
            "animation-delay",
            "animation-direction",
            "animation-duration",
            "animation-fill-mode",
            "animation-iteration-count",
            "animation-name",
            "animation-play-state",
            "animation-timing-function",

            // Background and border properties
            "background",
            "background-attachment",
            "background-clip",
            "background-color",
            "background-image",
            "background-origin",
            "background-position",
            "background-poistion-x",
            "background-poistion-y",
            "background-repeat",
            "background-size",
            "border",
            "border-color",
            "border-image",
            "border-image-outset",
            "border-image-repeat",
            "border-image-slice",
            "border-image-source",
            "border-image-width",
            "border-radius",
            "border-style",
            "border-width",
            "border-top",
            "border-top-color",
            "border-top-left-radius",
            "border-top-right-radius",
            "border-top-style",
            "border-top-width",
            "border-right",
            "border-right-color",
            "border-right-style",
            "border-right-width",
            "border-bottom",
            "border-bottom-color",
            "border-bottom-left-radius",
            "border-bottom-right-radius",
            "border-bottom-style",
            "border-bottom-width",
            "border-left",
            "border-left-color",
            "border-left-style",
            "border-left-width",
            "box-decoration-break",
            "box-shadow",

            // Filter effects, masking, image properties
            "filter",
            "image-orientation",
            "image-rendering",
            "image-resolution",
            "mask",
            "mask-type",
            "object-fit",
            "object-position",

            // Marquee properties
            "marquee-direction",
            "marquee-play-count",
            "marquee-speed",
            "marquee-style",

            // Scrollbar properties
            "scrollbar-3dlight-color",
            "scrollbar-arrow-color",
            "scrollbar-base-color",
            "scrollbar-darkshadow-color",
            "scrollbar-face-color",
            "scrollbar-highlight-color",
            "scrollbar-shadow-color",
            "scrollbar-track-color",

            // Speech properties
            "mark",
            "mark-after",
            "mark-before",
            "phonemes",
            "rest",
            "rest-after",
            "rest-before",
            "voice-balance",
            "voice-duration",
            "voice-pitch",
            "voice-pitch-range",
            "voice-rate",
            "voice-stress",
            "voice-volume",

            // Transform properties
            "transform",
            "transform-origin",
            "transform-style",
            "backface-visibility",
            "perspective",
            "perspective-origin",

            // Transitions properties
            "transition",
            "transition-delay",
            "transition-duration",
            "transition-property",
            "transition-timing-function",

            // Stack order and zoom properties
            "z-index",
            "zoom"
        ]],
        "rule-trailing-semicolon": [ 2, "always" ],
        "selector-combinator-space-after": [ 2, "always" ],
        "selector-combinator-space-before": [ 2, "always" ],
        "selector-list-comma-newline-after": [ 2, "always" ],
        "selector-list-comma-space-before": [ 2, "never" ],
        "selector-no-vendor-prefix": 2,
        "selector-pseudo-element-colon-notation": [ 2, "double" ],
        "selector-root-no-composition": 2,
        "string-quotes": [ 2, "double" ],
        "value-list-comma-newline-after": [ 2, "always-multi-line" ],
        "value-list-comma-space-after": [ 2, "always-single-line" ],
        "value-list-comma-space-before": [ 2, "never" ],
        "value-no-vendor-prefix": 2
    }
}